# Assignment

Q1. Write the NumPy program to create a 2d array with 6 on the border
and 0 inside?

    Expected OutputOriginal array-
    [ [6 6 6 6 6]
     [ 6 6 6 6 6]
     [ 6 6 6 6 6 ]
    [ 6 6 6 6 6 ]
    [ 6 6 6 6 ] ].
    6 on the border and 0 inside in the array-
    [[ 6 6 6 6 6]
    [ 6 0 0 0 6]
    [ 6 0 0 0 6]
    [ 6 0 0 0 6]
    [ 6 6 6 6 6]].

In [3]:
import numpy as np
two_dia=6*np.ones((5,5),dtype=int)
print(two_dia)
two_dia[1:-1,1:-1] = 0
print("\n6 on the border and 0 inside in the array\n")
print(two_dia)

[[6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]]

6 on the border and 0 inside in the array

[[6 6 6 6 6]
 [6 0 0 0 6]
 [6 0 0 0 6]
 [6 0 0 0 6]
 [6 6 6 6 6]]


Q2. Write the NumPy program to create a 8x8 matrix and fill it with the
checkerboard pattern?
    
    Checkerboard pattern-
    [[3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]].

In [33]:
import numpy as np

a=np.array(([3,9]*4+[9,3]*4)*4).reshape((8,8))
print(a)

[[3 9 3 9 3 9 3 9]
 [9 3 9 3 9 3 9 3]
 [3 9 3 9 3 9 3 9]
 [9 3 9 3 9 3 9 3]
 [3 9 3 9 3 9 3 9]
 [9 3 9 3 9 3 9 3]
 [3 9 3 9 3 9 3 9]
 [9 3 9 3 9 3 9 3]]


Q3. Write the NumPy program to create an empty and a full array.
 
     Expected Output-
    [[4.45057637e-308 1.78021527e-306 8.45549797e-307 1.37962049e-306]
    [1.11260619e-306 1.78010255e-306 9.79054228e-307 4.45057637e-308]
    [8.45596650e-307 9.34602321e-307 4.94065646e-322 0.00000000e+000]]
    [[6 6 6]
    [6 6 6]
    [6 6 6]]


In [3]:
import numpy as np
a=np.empty((3,4))
print(a)
b=np.full((3,3),6)
print(b)

[[6.23042070e-307 1.89146896e-307 1.37961302e-306 6.23053614e-307]
 [6.23053954e-307 9.34609790e-307 8.45593934e-307 9.34600963e-307]
 [1.86921143e-306 6.23061763e-307 8.45590539e-307 8.34445562e-308]]
[[6 6 6]
 [6 6 6]
 [6 6 6]]


Q4. Write the NumPy program to convert the values of Centigrade
degrees into the Fahrenheit degrees and the centigrade values are
stored in the NumPy array.
    
    Sample Array -[0, 12, 45.21 ,34, 99.91]
    Expected OutputValues in Fahrenheit degrees-
    [ 0. 12. 45.21 34. 99.91]
    Values in Centigrade degrees-
    [-17.77777778 -11.11111111 7.33888889 1.11111111 37.72777778]

In [4]:
import numpy as np
val=[0, 12, 45.21 ,34, 99.91]
Fahrenheit=np.array(val)
print("Fahrenheit degrees : {}".format(Fahrenheit))
print("Centigrade degress : {}".format(5*Fahrenheit/9 - 5*32/9))

Fahrenheit degrees : [ 0.   12.   45.21 34.   99.91]
Centigrade degress : [-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


Q5. Write the NumPy program to find the real and imaginary parts of an
array of complex numbers?

    Expected OutputOriginal array [ 1.00000000+0.j 0.70710678+0.70710678j]
    Real part of the array-
    [ 1. 0.70710678]
    Imaginary part of the array-
    [ 0. 0.70710678]

In [5]:
import numpy as np
x = np.sqrt([1+1j])
print("Original array:x ",x)
print("Real part of the array: {}".format(x.real))
print("Imaginary part of the array: {}".format(x.imag))


Original array:x  [1.09868411+0.45508986j]
Real part of the array: [1.09868411]
Imaginary part of the array: [0.45508986]


Q6. Write the NumPy program to test whether each element of a 1-D
array is also present in the second array?

    Expected OutputArray1: [ 0 10 20 40 60]
    Array2: [0, 40]
    Compare each element of array1 and array2
    [ True False False True False]


In [6]:
import numpy as np
array1=np.array([20,27,6,25,18,10])
array2=np.array([4,10,11])
print("Array 1 : {}".format(array1))
print("Array 2 : {}".format(array2))
print("Compare each element of array1 and array2:",np.in1d(array1, array2))

Array 1 : [20 27  6 25 18 10]
Array 2 : [ 4 10 11]
Compare each element of array1 and array2: [False False False False False  True]


Q7. Write the NumPy program to find common values between two
arrays?
    
    Expected OutputArray1: [ 0 10 20 40 60]
    Array2: [10, 30, 40]
    Common values between two arrays-
    [10 40]

In [7]:
import numpy as np
array1=np.array([20,27,6,25,18,10])
array2=np.array([4,10,11])
print("Array 1 : {}".format(array1))
print("Array 2 : {}".format(array2))
print("Unique elements of the above array:",np.intersect1d(array1, array2))

Array 1 : [20 27  6 25 18 10]
Array 2 : [ 4 10 11]
Unique elements of the above array: [10]


Q8. Write the NumPy program to get the unique elements of an array?

    Expected OutputOriginal array-
    [10 10 20 20 30 30]
    Unique elements of the above array-
    [10 20 30]
    P a g e 14 | 44
    Original array-
    [[1 1]
    [2 3]]
    Unique elements of the above array-
    [1 2 3]

In [8]:
import numpy as n
num=n.array([27,20,6,25,6,27,20,18,11,4,19,29])
print("Original array : {}".format(num))
print("\nUnique elements of the above array {} ".format(n.unique(num)))

num1=n.array([[1,2,3],[3,2,1],[4,5,6],[6,7,8]])
print("\nOriginal array : {}".format(num1))
print("\nUnique elements of the above array :{} ".format(n.unique(num1)))

Original array : [27 20  6 25  6 27 20 18 11  4 19 29]

Unique elements of the above array [ 4  6 11 18 19 20 25 27 29] 

Original array : [[1 2 3]
 [3 2 1]
 [4 5 6]
 [6 7 8]]

Unique elements of the above array :[1 2 3 4 5 6 7 8] 


Q9. Write the NumPy program to find the set exclusive-or of two arrays.
Set exclusive-or will return the sorted, unique values that are in
only one (not both) of the input arrays?

    Array1- [ 0 10 20 40 60 80]
    Array2- [10, 30, 40, 50, 70]
    Unique values that are in only one (not both) of the input arrays-
    [ 0 20 30 50 60 70 80]

In [9]:
import numpy as np
array1=np.array([20,27,6,25,18,10])
array2=np.array([4,10,11])
print("Array 1 : {}".format(array1))
print("Array 2 : {}".format(array2))
print("Unique values that are in only one (not both) of the input arrays:",np.setxor1d(array1, array2))

Array 1 : [20 27  6 25 18 10]
Array 2 : [ 4 10 11]
Unique values that are in only one (not both) of the input arrays: [ 4  6 11 18 20 25 27]


Q10. Write the NumPy program to test if all elements in an array
evaluate to True ?
 
Note: 0 evaluates to False in NumPy

In [10]:
import numpy as n
x=n.array([11, 1, 0.0, -27])
y=n.array([1,True,27,20,6])
print("Test if all elements in an array are True or False x : {} ".format(n.all(x)))
print("Test if all elements in an array are True or False y : {} ".format(n.all(y)))


Test if all elements in an array are True or False x : False 
Test if all elements in an array are True or False y : True 


Q11. Write the NumPy program to test whether any array element along
the given axis evaluates to True?
 
Note: 0 evaluates to False in NumPy

In [20]:
import numpy as n
x=n.array([11, 1, 0.0, -27])
y=n.array([1,True,27,20,6])
z=n.array([0,0,False,False])
print("To test whether all elemrnts in the array array are False x : {} ".format(n.any(x)))
print("To test whether all elemrnts in the array array are False y : {} ".format(n.any(y)))
print("To test whether all elemrnts in the array array are False y : {} ".format(n.any(z)))


To test whether all elemrnts in the array array are False x : True 
To test whether all elemrnts in the array array are False y : True 
To test whether all elemrnts in the array array are False y : False 


Q12. Write the NumPy program to construct an array by repeating?

    Sample array- [1, 2, 3, 4]
    Expected OutputOriginal array
    [1, 2, 3, 4]
    Repeating 2 times
    [1 2 3 4 1 2 3 4]
    Repeating 3 times
    [1 2 3 4 1 2 3 4 1 2 3 4]

In [25]:
import numpy as n
x=n.array([20,27,6,25,18,10]*2)
print("Repeating two times:{}".format(x))
y=n.array([20,27,6,25,18,10]*3)
print("Repeating three times:{}".format(y))

#using tile
a=n.array([20,27,6,25,18,10])
print("Repaeating two times using tile",np.tile(a, 2))
print("Repaeating three times using tile",np.tile(a, 3))

Repeating two times:[20 27  6 25 18 10 20 27  6 25 18 10]
Repeating three times:[20 27  6 25 18 10 20 27  6 25 18 10 20 27  6 25 18 10]
Repaeating two times using tile [20 27  6 25 18 10 20 27  6 25 18 10]
Repaeating three times using tile [20 27  6 25 18 10 20 27  6 25 18 10 20 27  6 25 18 10]


Q13. Write the NumPy program to find the indices of the maximum and
minimum values with the given axis of an array?

    Original array- [1 2 3 4 5 6]
    Maximum Values- 5
    Minimum Values- 0

In [26]:
import numpy as n
x=n.array([20,27,6,25,18,10])
print("Original array:",x)
print("Maximum Value index position: ",n.argmax(x))
print("Minimum Value index position: ",n.argmin(x))


Original array: [20 27  6 25 18 10]
Maximum Value index position:  1
Minimum Value index position:  2


Q14. Write the NumPy program compare two arrays using numpy?

    Array a- [1 2]
    Array b- [4 5]
    a > b
    [False False]
    a >= b
    [False False]
    a < b
    [ True True]
    a <= b
    [ True True]


In [27]:
import numpy as n
x=n.array([20,27,6,25,18,10])
y=n.array([20,27,6,25,18,10])*2
print("Array x : {}\nArray y : {}".format(x,y))
print("\nx>y",n.greater(x, y))
print("\nx>=y",n.greater_equal(x, y))
print("\nx<y",n.less(x, y))
print("\nx<=y",n.less_equal(x, y))

Array x : [20 27  6 25 18 10]
Array y : [40 54 12 50 36 20]

x>y [False False False False False False]

x>=y [False False False False False False]

x<y [ True  True  True  True  True  True]

x<=y [ True  True  True  True  True  True]


Q15. Write the NumPy program to sort an along the first, last axis of an
array?

    Sample array- [[2,5],[4,4]]
    Expected OutputOriginal array:
    [[4 6]
    [2 1]]
    Sort along the first axis:
    [[2 1]
    [4 6]]
    Sort along the last axis-
    [[1 2]
    [4 6]]

In [28]:
import numpy as n
arr=n.array([[20,27,6],[25,18,4]])
x=n.sort(arr,axis=0)
print("Sort along the first axis:\n",x)
y=n.sort(arr,axis=1)
print("Sort along the last axis:\n",y)

Sort along the first axis:
 [[20 18  4]
 [25 27  6]]
Sort along the last axis:
 [[ 6 20 27]
 [ 4 18 25]]


Q16. Write the NumPy program to sort pairs of first name and last name
return their indices (first by last name, then by first name).

    first_names - ( Betsey, Shelley, Lanell, Genesis, Margery )
    last_names - ( Battle, Brien, Plotner, Stahl, Woolum )
    Expected Output-
    [1 3 2 4 0]

In [29]:
import numpy as n
F_name=n.array(['Data','Science','Machine'])
L_name=n.array(["Deep",'Learning','Learning'])
Full_name=n.lexsort((F_name,L_name))
print(Full_name)

[0 2 1]


Q17. Write the NumPy program to get the values and indices of the
elements that are bigger than 10 in the given array?

    Original array-
    [[ 0 10 20]
    [20 30 40]]
    Values bigger than 10 = [20 20 30 40]
    Their indices are (array([0, 1, 1, 1]), array([2, 0, 1, 2]))

In [31]:
import numpy as np
x = np.array([[0, 10, 20], [20, 30, 40]])
print("Original array: ")
print(x)
print("Values bigger than 10 =", x[x>10])
print("Indicies : ",np.nonzero(x > 10))

Original array: 
[[ 0 10 20]
 [20 30 40]]
Values bigger than 10 = [20 20 30 40]
Indicies :  (array([0, 1, 1, 1], dtype=int64), array([2, 0, 1, 2], dtype=int64))


Q18. Write the NumPy program to find the memory size of a NumPy
array?

    Expected Output128 bytes


In [32]:
import numpy as np
n = np.zeros((4,4))
print("{} bytes".format(n.size * n.itemsize))

128 bytes


## Great Job!